"use client";

import { useEffect, useState } from "react";

export default function TestQRPage() {
  const [qrImageDataUrl, setQrImageDataUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/test-qr")
      .then((res) => res.json())
      .then((data) => {
        if (data.error) setError(data.error);
        else setQrImageDataUrl(data.qrImageDataUrl);
      })
      .catch((err) => setError(err.message));
  }, []);

  return (
    <div style={{ padding: 40, fontFamily: "sans-serif", maxWidth: 500, margin: "0 auto" }}>
      <h1 style={{ fontSize: 24, marginBottom: 20 }}>PAY by square - Test (Official API)</h1>

      <div style={{ marginBottom: 20, fontSize: 14, color: "#666" }}>
        <p><strong>IBAN:</strong> SK13 0900 0000 0052 2138 0177</p>
        <p><strong>BIC/SWIFT:</strong> GIBASKBX</p>
        <p><strong>Beneficiary:</strong> [Your Agency]</p>
        <p><strong>Amount:</strong> €1.00</p>
        <p><strong>Currency:</strong> EUR</p>
        <p><strong>Variable Symbol (VS):</strong> 123456</p>
        <p><strong>Constant Symbol (KS):</strong> 0308</p>
        <p><strong>Due Date:</strong> {new Date().toISOString().split("T")[0]}</p>
        <p><strong>Note:</strong> Test payment - [Your Agency]</p>
      </div>

      {error && <p style={{ color: "red" }}>Error: {error}</p>}
      {!qrImageDataUrl && !error && <p>Loading...</p>}

      {qrImageDataUrl && (
        <div style={{ background: "white", padding: 20, borderRadius: 8, display: "inline-block" }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={qrImageDataUrl} alt="PAY by square QR" width={250} height={250} />
        </div>
      )}

      <p style={{ marginTop: 20, fontSize: 13, color: "#888" }}>
        This QR is generated by the official bsqr.co API. Scan with your banking app to verify.
      </p>
    </div>
  );
}
